"""changed file db

Revision ID: 0235b4a11230
Revises: efefe9ac34b7
Create Date: 2024-08-01 00:03:24.942433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0235b4a11230'
down_revision = 'efefe9ac34b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('fk_file_course_id_course', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_file_course_id_course', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
