"""allowed nullable answer for FITB

Revision ID: 115642377bda
Revises: 236274b50adf
Create Date: 2024-06-25 20:29:58.976910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115642377bda'
down_revision = '236274b50adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fill_in_the_blank_question', schema=None) as batch_op:
        batch_op.alter_column('answers',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fill_in_the_blank_question', schema=None) as batch_op:
        batch_op.alter_column('answers',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
