"""Added fill in the blank question

Revision ID: 236274b50adf
Revises: 3f368b7ef71f
Create Date: 2024-06-25 20:25:14.360991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236274b50adf'
down_revision = '3f368b7ef71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fill_in_the_blank_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question.id'], name=op.f('fk_fill_in_the_blank_question_id_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fill_in_the_blank_question'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fill_in_the_blank_question')
    # ### end Alembic commands ###
