"""Disallowed nullable answer for FITB

Revision ID: 256588c64587
Revises: 115642377bda
Create Date: 2024-06-25 20:34:13.620726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256588c64587'
down_revision = '115642377bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fill_in_the_blank_question', schema=None) as batch_op:
        batch_op.alter_column('answers',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fill_in_the_blank_question', schema=None) as batch_op:
        batch_op.alter_column('answers',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
