"""added field to text attempt

Revision ID: 54547e09748a
Revises: c333a4a31616
Create Date: 2024-07-03 20:48:17.956545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54547e09748a'
down_revision = 'c333a4a31616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_user_input', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_attempt', schema=None) as batch_op:
        batch_op.drop_column('original_user_input')

    # ### end Alembic commands ###
