"""beginning of summer db

Revision ID: 9e36b0fe341b
Revises: 
Create Date: 2022-06-08 11:20:38.269012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e36b0fe341b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_description'), 'course', ['description'], unique=False)
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=True)
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=False)
    op.create_table('textbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('edition', sa.Integer(), nullable=True),
    sa.Column('authors', sa.String(length=100), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_textbook_authors'), 'textbook', ['authors'], unique=False)
    op.create_index(op.f('ix_textbook_isbn'), 'textbook', ['isbn'], unique=False)
    op.create_index(op.f('ix_textbook_publisher'), 'textbook', ['publisher'], unique=False)
    op.create_index(op.f('ix_textbook_title'), 'textbook', ['title'], unique=False)
    op.create_index(op.f('ix_textbook_url'), 'textbook', ['url'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('instructor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_description'), 'assessment', ['description'], unique=False)
    op.create_index(op.f('ix_assessment_title'), 'assessment', ['title'], unique=False)
    op.create_table('assigned_textbooks',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'textbook_id')
    )
    op.create_table('course_topics',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'topic_id')
    )
    op.create_table('enrollments',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    op.create_table('objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_description'), 'objective', ['description'], unique=True)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GENERIC', 'TEXTBOOK_SECTION', 'CLASS_MEETING', name='sourcetype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_title'), 'source', ['title'], unique=False)
    op.create_table('assessment_objectives',
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], )
    )
    op.create_table('assessment_topics',
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    op.create_table('class_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GENERIC', 'SHORT_ANSWER', 'MULTIPLE_CHOICE', 'CODE_JUMBLE', 'AUTO_CHECK', name='questiontype'), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_objectives',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objective.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], )
    )
    op.create_table('textbook_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('textbook_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_sources',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    op.create_table('answer_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], )
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GENERIC', 'TEXT', 'SELECTION', name='responsetype'), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('next_attempt', sa.Date(), nullable=False),
    sa.Column('e_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_check_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('regex', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_jumble_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jumble_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('correct_indent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiple_choice_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_answer_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selection_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['answer_option.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_attempt')
    op.drop_table('selection_attempt')
    op.drop_table('short_answer_question')
    op.drop_table('multiple_choice_question')
    op.drop_table('jumble_block')
    op.drop_table('code_jumble_question')
    op.drop_table('auto_check_question')
    op.drop_table('attempt')
    op.drop_table('assessment_questions')
    op.drop_table('answer_option')
    op.drop_table('topic_sources')
    op.drop_table('textbook_section')
    op.drop_table('source_objectives')
    op.drop_table('question')
    op.drop_table('class_meeting')
    op.drop_table('assessment_topics')
    op.drop_table('assessment_objectives')
    op.drop_index(op.f('ix_source_title'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_objective_description'), table_name='objective')
    op.drop_table('objective')
    op.drop_table('enrollments')
    op.drop_table('course_topics')
    op.drop_table('assigned_textbooks')
    op.drop_index(op.f('ix_assessment_title'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_description'), table_name='assessment')
    op.drop_table('assessment')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('topic')
    op.drop_index(op.f('ix_textbook_url'), table_name='textbook')
    op.drop_index(op.f('ix_textbook_title'), table_name='textbook')
    op.drop_index(op.f('ix_textbook_publisher'), table_name='textbook')
    op.drop_index(op.f('ix_textbook_isbn'), table_name='textbook')
    op.drop_index(op.f('ix_textbook_authors'), table_name='textbook')
    op.drop_table('textbook')
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_index(op.f('ix_course_name'), table_name='course')
    op.drop_index(op.f('ix_course_description'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
