"""orig prompt

Revision ID: c333a4a31616
Revises: 256588c64587
Create Date: 2024-07-03 18:15:05.674678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c333a4a31616'
down_revision = '256588c64587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fill_in_the_blank_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_prompt_before_reformat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fill_in_the_blank_question', schema=None) as batch_op:
        batch_op.drop_column('original_prompt_before_reformat')

    # ### end Alembic commands ###
