"""Added file upload to assessments

Revision ID: efefe9ac34b7
Revises: 54547e09748a
Create Date: 2024-07-30 14:41:13.892647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efefe9ac34b7'
down_revision = '54547e09748a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name=op.f('fk_file_assessment_id_assessment')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_file_course_id_course')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
