name: End-to-End Tests (Cypress)
on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: nikolaik/python-nodejs:python3.10-nodejs16-slim

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      elasticsearch:
        image: bitnami/elasticsearch:7.17.4
        env:
          discovery.type: single-node

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cypress cependencies
        run: apt-get update && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Create Flask instance config
        run: |
          mkdir instance
          echo "ELASTICSEARCH_URL = 'http://elasticsearch:9200'" > instance/config.py
      - name: Start Flask and run Cypress
        uses: cypress-io/github-action@v5
        env:
          APP_CONFIG_CLASS: config.E2ETestingConfig
        with:
          start: flask run
          wait-on: 'http://localhost:5000'
          env: video=false,screenshotOnRunFailure=false
